AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello_world

  Sample SAM Template for hello_world

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7

      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                  - dynamodb:GetItem
              Resource: !GetAtt ConfigVersionTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                  - dynamodb:GetItem
              Resource: !GetAtt ConfigsTable.Arn

      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  ConfigsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: config_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: config_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ConfigVersionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: current
          AttributeType: S
      KeySchema:
        -
          AttributeName: current
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  HelloWorldConfigsTable:
    Description: "DynamoDB table holding config versions"
    Value: !GetAtt ConfigsTable.Arn
  HelloWorldConfigVersionTable:
    Description: "DynamoDB table holding the current config version to use"
    Value: !GetAtt ConfigVersionTable.Arn
